/*
 * This source file was generated by the Gradle 'init' task
 */
package me.eigenraven.mcfsck;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.ByteBuffer;

import static org.junit.jupiter.api.Assertions.*;

class AppTest {

    @Test
    void mcrFixTest() throws IOException {
        Class<AppTest> cls = AppTest.class;
        final byte[] dataOk = cls.getResourceAsStream("test-ok.mca").readAllBytes();
        final byte[] dataBad = cls.getResourceAsStream("test-bad.mca").readAllBytes();
        final byte[] dataFixed = cls.getResourceAsStream("test-fixed.mca").readAllBytes();
        System.out.println("Testing ok");
        assertFalse(App.fixMcr("ok", ByteBuffer.wrap(dataOk)));
        System.out.println("Testing err");
        final ByteBuffer bad = ByteBuffer.wrap(dataBad.clone());
        assertTrue(App.fixMcr("bad", bad));
        assertArrayEquals(bad.array(), dataFixed);
    }
}
